services:
  db:
    image: postgres:16
    env_file:
      - .env.dev
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  api:
    build: .
    image: api:1
    networks:
      - backend
    ports:
      - '8080:8080'
    env_file:
      - .env.dev
    volumes:
      - ./src:/service/src
      - ./migrations:/service/migrations
      - ./tests:/service/tests
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:

volumes:
  postgres_data:
